/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import interact.Login;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.Border;

/**
 *
 * @author KhanhLong
 */
public class formMain extends javax.swing.JFrame {

    /**
     * Creates new form formMain
     */
    private JScrollPane scrollPane = new JScrollPane();

    public formMain() {
        initComponents();
        this.setLocationRelativeTo(this);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/iconMain.png")));
        setTitle("Perfume Store Management System");
        permissing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dtContent = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemChangePass = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuDirector = new javax.swing.JMenu();
        menuItemAddManager = new javax.swing.JMenuItem();
        nemuItemManagementStore = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuManagement = new javax.swing.JMenu();
        menuItemManagementSale = new javax.swing.JMenuItem();
        menuItemManagementBill = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        menuInventory = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        menuItemCategory_Product = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuSales = new javax.swing.JMenu();
        menuCreateBill = new javax.swing.JMenuItem();
        menuItemSearchProduct = new javax.swing.JMenuItem();
        menuItemCustomer = new javax.swing.JMenuItem();
        menuItemInformationSale = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BannerMain.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("About"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Perfume Store ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText(". Le Tuan Vu");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team.png"))); // NOI18N
        jLabel5.setText("GROUP 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText(". Nguyen Quang Trung");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText(". Nguyen Khanh Long");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText(". Hoang Minh Tuan");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("        Management System Version 1.0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat.png"))); // NOI18N
        jLabel9.setText("Contact Us");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText(" Le Tuan Vu ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Nguyen Quang Trung");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Nguyen Khanh Long");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Hoang Minh Tuan");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("tuanvumustache@gmail.com - 01682015795");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Kevinguyen510@gmail.com - 01676811997");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("khanhlong1708@gmail.com - 0906666821");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("hoangminhtuan140295 - 0933824283");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dtContent.setBackground(new java.awt.Color(240, 240, 240));
        dtContent.setAutoscrolls(true);
        dtContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout dtContentLayout = new javax.swing.GroupLayout(dtContent);
        dtContent.setLayout(dtContentLayout);
        dtContentLayout.setHorizontalGroup(
            dtContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dtContentLayout.setVerticalGroup(
            dtContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconSystem.png"))); // NOI18N
        jMenu1.setText("System");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuItemChangePass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconChangePassword.png"))); // NOI18N
        menuItemChangePass.setText("Change password");
        menuItemChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChangePassActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemChangePass);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconLogout.png"))); // NOI18N
        jMenuItem2.setText("Log out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExit.png"))); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        menuDirector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconDirector.png"))); // NOI18N
        menuDirector.setText("Director");
        menuDirector.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuItemAddManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemAddManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconNewUser.png"))); // NOI18N
        menuItemAddManager.setText("Create New Manager /Inventory         ");
        menuItemAddManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddManagerActionPerformed(evt);
            }
        });
        menuDirector.add(menuItemAddManager);

        nemuItemManagementStore.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nemuItemManagementStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconStore.png"))); // NOI18N
        nemuItemManagementStore.setText("Management Store     ");
        nemuItemManagementStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nemuItemManagementStoreActionPerformed(evt);
            }
        });
        menuDirector.add(nemuItemManagementStore);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconReport.png"))); // NOI18N
        jMenuItem5.setText("View Report Manager");
        menuDirector.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconReport2.png"))); // NOI18N
        jMenuItem6.setText("View Report Inventory");
        menuDirector.add(jMenuItem6);

        jMenuBar1.add(menuDirector);

        menuManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconManager.png"))); // NOI18N
        menuManagement.setText("Manager");
        menuManagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuItemManagementSale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemManagementSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconManagementSales.png"))); // NOI18N
        menuItemManagementSale.setText("  Management Sales  ");
        menuItemManagementSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManagementSaleActionPerformed(evt);
            }
        });
        menuManagement.add(menuItemManagementSale);

        menuItemManagementBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemManagementBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconManagementBill.png"))); // NOI18N
        menuItemManagementBill.setText("  Management Bills  ");
        menuItemManagementBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManagementBillActionPerformed(evt);
            }
        });
        menuManagement.add(menuItemManagementBill);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconReport.png"))); // NOI18N
        jMenuItem17.setText("View Report Sales");
        menuManagement.add(jMenuItem17);

        jMenuBar1.add(menuManagement);

        menuInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconIventory.png"))); // NOI18N
        menuInventory.setText("Inventory");
        menuInventory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconInventoryManagement.png"))); // NOI18N
        jMenuItem14.setText("View Inventory Status");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        menuInventory.add(jMenuItem14);

        menuItemCategory_Product.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCategory_Product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconManagementItem.png"))); // NOI18N
        menuItemCategory_Product.setText("Management Categories/ Products");
        menuItemCategory_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCategory_ProductActionPerformed(evt);
            }
        });
        menuInventory.add(menuItemCategory_Product);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconReport2.png"))); // NOI18N
        jMenuItem16.setText("View Report Inventory");
        menuInventory.add(jMenuItem16);

        jMenuBar1.add(menuInventory);

        menuSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconStaff.png"))); // NOI18N
        menuSales.setText("Sales");
        menuSales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuCreateBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCreateBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconCreateBill.png"))); // NOI18N
        menuCreateBill.setText("Create Bill              ");
        menuCreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateBillActionPerformed(evt);
            }
        });
        menuSales.add(menuCreateBill);

        menuItemSearchProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemSearchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconSearch.png"))); // NOI18N
        menuItemSearchProduct.setText("Search Products");
        menuItemSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchProductActionPerformed(evt);
            }
        });
        menuSales.add(menuItemSearchProduct);

        menuItemCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconCustomer.png"))); // NOI18N
        menuItemCustomer.setText("Customers");
        menuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCustomerActionPerformed(evt);
            }
        });
        menuSales.add(menuItemCustomer);

        menuItemInformationSale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemInformationSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconView.png"))); // NOI18N
        menuItemInformationSale.setText("View Infotmation Sale");
        menuItemInformationSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInformationSaleActionPerformed(evt);
            }
        });
        menuSales.add(menuItemInformationSale);

        jMenuBar1.add(menuSales);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconHelp.png"))); // NOI18N
        jMenu6.setText("Help");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconSupport.png"))); // NOI18N
        jMenuItem7.setText("Support");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconAbout.png"))); // NOI18N
        jMenuItem8.setText("About");
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(dtContent)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dtContent))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuItemAddManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddManagerActionPerformed
        // TODO add your handling code here:
        frmCreateNewManager create = new frmCreateNewManager();
        dtContent.add(create);
        create.show();
        try {
            create.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemAddManagerActionPerformed

    private void menuItemChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChangePassActionPerformed
        // TODO add your handling code here:
        frmChangePassword changePass = new frmChangePassword();
        dtContent.add(changePass);
        changePass.show();
    }//GEN-LAST:event_menuItemChangePassActionPerformed

    private void menuCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateBillActionPerformed
        // TODO add your handling code here:
        frmCreateBill createBill = new frmCreateBill();
        dtContent.add(createBill);
        createBill.show();
        try {
            createBill.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCreateBillActionPerformed

    private void nemuItemManagementStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nemuItemManagementStoreActionPerformed
        // TODO add your handling code here:
        frmCreateNewStore createStore = new frmCreateNewStore();
        dtContent.add(createStore);
        createStore.show();
        try {
            createStore.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nemuItemManagementStoreActionPerformed

    private void menuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCustomerActionPerformed
        // TODO add your handling code here:
        frmCustomer customer = new frmCustomer();
        dtContent.add(customer);
        customer.show();
        try {
            customer.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemCustomerActionPerformed

    private void menuItemInformationSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInformationSaleActionPerformed
        // TODO add your handling code here:
        frmInformationSales informationSales = new frmInformationSales();
        dtContent.add(informationSales);
        informationSales.show();
        try {
            informationSales.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemInformationSaleActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        frmInventoryManagement inventoryManagement = new frmInventoryManagement();
        dtContent.add(inventoryManagement);
        inventoryManagement.show();
        try {
            inventoryManagement.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void menuItemManagementBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManagementBillActionPerformed
        // TODO add your handling code here:
        frmManagementBill managementBill = new frmManagementBill();
        dtContent.add(managementBill);
        managementBill.show();
        try {
            managementBill.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemManagementBillActionPerformed

    private void menuItemCategory_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCategory_ProductActionPerformed
        // TODO add your handling code here:
        frmCategory_Product categoryProduct = new frmCategory_Product();
        dtContent.add(categoryProduct);
        categoryProduct.show();
        try {
            categoryProduct.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemCategory_ProductActionPerformed

    private void menuItemManagementSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManagementSaleActionPerformed
        // TODO add your handling code here:
        frmManagementSales managementSale = new frmManagementSales();
        dtContent.add(managementSale);
        managementSale.show();
        try {
            managementSale.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemManagementSaleActionPerformed

    private void menuItemSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchProductActionPerformed
        // TODO add your handling code here:
        frmSearchProducts searchProduct = new frmSearchProducts();
        dtContent.add(searchProduct);
        searchProduct.show();
        try {
            searchProduct.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(formMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemSearchProductActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        formLogin log = new formLogin();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    public void permissing() {
        if (Login.getAdminID() == null && Login.getUsername() == null && Login.getPassword() == null && Login.getPermit() == null) {
            int i = JOptionPane.showConfirmDialog(this, "Truy cập đã bị chặn, yêu cầu đăng nhập trước.");
            if (i == JOptionPane.YES_OPTION) {
                System.exit(1);
            }
        } else if (Login.getPermit().equals("DI")) {
            menuDirector.setVisible(true);
            menuInventory.setVisible(false);
            menuManagement.setVisible(false);
            menuSales.setVisible(false);
        } else if (Login.getPermit().equals("MN")) {
            menuDirector.setVisible(false);
            menuInventory.setVisible(false);
            menuManagement.setVisible(true);
            menuSales.setVisible(false);
        } else if (Login.getPermit().equals("IV")) {
            menuDirector.setVisible(false);
            menuInventory.setVisible(true);
            menuManagement.setVisible(false);
            menuSales.setVisible(false);
        } else {
            menuDirector.setVisible(false);
            menuInventory.setVisible(false);
            menuManagement.setVisible(false);
            menuSales.setVisible(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuCreateBill;
    private javax.swing.JMenu menuDirector;
    private javax.swing.JMenu menuInventory;
    private javax.swing.JMenuItem menuItemAddManager;
    private javax.swing.JMenuItem menuItemCategory_Product;
    private javax.swing.JMenuItem menuItemChangePass;
    private javax.swing.JMenuItem menuItemCustomer;
    private javax.swing.JMenuItem menuItemInformationSale;
    private javax.swing.JMenuItem menuItemManagementBill;
    private javax.swing.JMenuItem menuItemManagementSale;
    private javax.swing.JMenuItem menuItemSearchProduct;
    private javax.swing.JMenu menuManagement;
    private javax.swing.JMenu menuSales;
    private javax.swing.JMenuItem nemuItemManagementStore;
    // End of variables declaration//GEN-END:variables
}
